### PR TITLE
feat(supporter) New Supporters

### PR DESCRIPTION
**Pull request by SerStars**
Added new supporters

Automated with Enmity Addons Bot
Created by SerStars

### CODE REVIEW

**Comment by colin273** [comment]
Let's try this again

**Comment by catnipjson** [comment]
haha

**Comment by SerStars** [comment]
> haha
im gonna find you

**Comment by catnipjson** [comment]
Added new supporters

Automated by Enmity Addons
Created by SerStars

**Comment by SerStars** [comment]
> Added new supporters
> 
> Automated by Enmity Addons Created by SerStars

YOU SCARED ME FOR A SEC FCK YOU

**Comment by catnipjson** [comment]
haha

**Comment by catnipjson** [comment]
ok maybe shut up

**Comment by acquitelol** [comment]
Added new supporters

Automated by Enmity Addons
Created by SerStars

**Comment by catnipjson** [comment]
Added new supporters

Automated with Enmity Addons Bot
Created by SerStars

**Pull request closed without merging**
